name: Beta branch to GitHub Pages
on:
  push:
    branches:
      - svelte-mapbox-rewrite
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
        env:
          API_KEY: 2J6__p_IWwUmOHYMKuMYjw
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          TARGET_FOLDER: beta